---
title: "Results of maximum likelihood modeling of Manos' delay discounting data"
output:
  html_document:
    df_print: paged
---

```{r setup}
knitr::opts_chunk$set(eval = FALSE, include = FALSE)
knitr::opts_knit$set(root.dir = normalizePath(".."))
```

```{r include=FALSE}
library(tidyverse)

plot_pp = function(dat_tmp){
  dat_pl = dat_tmp %>%
    group_by(amount,delay) %>%
    summarise(obs = mean(choose_a),
              obs_se = sd(choose_a)/sqrt(length(choose_a)),
              pred = mean(p_a))
  
  print(
    ggplot(dat_pl,aes(x=delay)) +
      geom_point(aes(y=obs),colour="red") +
      geom_errorbar(aes(ymin=obs-obs_se,ymax=obs+obs_se),colour="red") +
      geom_line(aes(y=pred),colour="blue") +
      facet_wrap(~amount)
  )
}

get_bic = function(dat_tmp){
  #make sure there are no cases where p_a = 0 or 1
  p_a = pmin(pmax(dat_tmp$p_a,0.001),0.999) 
  #calculate summed log likelihood
  lnl = sum(log(dat_tmp$choose_a*p_a + (1-dat_tmp$choose_a)*(1-p_a)))
  #compute number of parameters (based on how many columns are between observed choice and predicted choice)
  nparms = grep("p_a",names(dat_tmp))-grep("choose_a",names(dat_tmp)) - 1
  #compute bic
  bic = log(length(p_a))*nparms - 2*lnl 
  return(c(lnl=lnl,nparms=nparms,bic=bic))
}

#output for storing fit stats
output=list()
ctr=0
```


# Hyperbolic Model

```{r echo=FALSE}
load(file="data/derived/fit_ML_hyperbolic.RData")
plot_pp(dat_tmp)
ctr=ctr+1
output[[ctr]]=get_bic(dat_tmp)
```

# Exponential Model
```{r echo=FALSE}
load(file="data/derived/fit_ML_exponential.RData")
plot_pp(dat_tmp)
ctr=ctr+1
output[[ctr]]=get_bic(dat_tmp)
```

# Green & Myerson Hyperbolic
```{r echo=FALSE}
load(file="data/derived/fit_ML_hyperbolic_gm.RData")
plot_pp(dat_tmp)
ctr=ctr+1
output[[ctr]]=get_bic(dat_tmp)
```

# Proportional Difference Model
```{r echo=FALSE}
load(file="data/derived/fit_ML_prop_diff.RData")
plot_pp(dat_tmp)
ctr=ctr+1
output[[ctr]]=get_bic(dat_tmp)
```

# Tradeoff Model
```{r echo=FALSE}
load(file="data/derived/fit_ML_tradeoff.RData")
plot_pp(dat_tmp)
ctr=ctr+1
output[[ctr]]=get_bic(dat_tmp)
```

# ITCH Model
```{r echo=FALSE}
load(file="data/derived/fit_ML_ITCH.RData")
plot_pp(dat_tmp)
ctr=ctr+1
output[[ctr]]=get_bic(dat_tmp)
```

# Constant Sensitivity Model (Ebert & Prelec, 2007)
```{r echo=FALSE}
load(file="data/derived/fit_ML_const_sens.RData")
plot_pp(dat_tmp)
ctr=ctr+1
output[[ctr]]=get_bic(dat_tmp)
```

# Hyperboloid Model (Mazur, 1987)
```{r echo=FALSE}
load(file="data/derived/fit_ML_mazur1987.RData")
plot_pp(dat_tmp)
ctr=ctr+1
output[[ctr]]=get_bic(dat_tmp)
```

# Loewenstein & Prelec's (1992) Model
```{r echo=FALSE}
load(file="data/derived/fit_ML_leowenstein1992.RData")
plot_pp(dat_tmp)
ctr=ctr+1
output[[ctr]]=get_bic(dat_tmp)
```

# Double Exponential Model (McClure et al., 2007)
```{r echo=FALSE}
load(file="data/derived/fit_ML_mcclure2007.RData")
plot_pp(dat_tmp)
ctr=ctr+1
output[[ctr]]=get_bic(dat_tmp)
```

# Additive Utility Model (Killeen, 2009)
```{r echo=FALSE}
load(file="data/derived/fit_ML_killeen2009.RData")
plot_pp(dat_tmp)
ctr=ctr+1
output[[ctr]]=get_bic(dat_tmp)
```

# Model Comparison
```{r echo=FALSE}
library(knitr)
model = c('Hyperbolic','Exponential','Green & Myerson Hyperbolic','Proportional Difference','Tradeoff','ITCH',
              'Constant Sensitivity','Hyerboloid (Mazur, 1987)','Loewenstein & Prelec (1992)','Double Exponential (McClure et al., 2007)',
              'Additive Utility (Killeen, 2009)')

results=t(as.data.frame(output))
results2 = as.data.frame(cbind(model,results))
results3 = results2 %>%
  mutate(lnl = as.numeric(as.character(lnl)),
         nparms = as.numeric(as.character(nparms)),
         bic = as.numeric(as.character(bic))) %>%
  arrange(bic)
kable(results3,caption="Results of Model Comparisons")

```
