// Code generated by Stan version 2.18.1

#include <stan/model/model_header.hpp>

namespace ITCH_mpi_model_namespace {

using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;

static int current_statement_begin__;

stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "/QRISdata/Q0992/models/ITCH_mpi.stan");
    reader.add_event(150, 148, "end", "/QRISdata/Q0992/models/ITCH_mpi.stan");
    return reader;
}

template <typename T0__, typename T1__, typename T2__>
Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__, T2__>::type, Eigen::Dynamic,1>
likelihood(const Eigen::Matrix<T0__, Eigen::Dynamic,1>& phi,
               const Eigen::Matrix<T1__, Eigen::Dynamic,1>& theta,
               const std::vector<T2__>& real_data,
               const std::vector<int>& int_data, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 10;
        int Nvalid(0);
        (void) Nvalid;  // dummy to suppress unused var warning

        stan::math::fill(Nvalid, std::numeric_limits<int>::min());
        stan::math::assign(Nvalid,get_base1(int_data,1,"int_data",1));
        current_statement_begin__ = 11;
        int Nplaces(0);
        (void) Nplaces;  // dummy to suppress unused var warning

        stan::math::fill(Nplaces, std::numeric_limits<int>::min());
        stan::math::assign(Nplaces,get_base1(int_data,2,"int_data",1));
        current_statement_begin__ = 14;
        local_scalar_t__ B1;
        (void) B1;  // dummy to suppress unused var warning

        stan::math::initialize(B1, DUMMY_VAR__);
        stan::math::fill(B1,DUMMY_VAR__);
        stan::math::assign(B1,(get_base1(phi,1,"phi",1) + (get_base1(phi,2,"phi",1) * get_base1(theta,1,"theta",1))));
        current_statement_begin__ = 15;
        local_scalar_t__ BxA;
        (void) BxA;  // dummy to suppress unused var warning

        stan::math::initialize(BxA, DUMMY_VAR__);
        stan::math::fill(BxA,DUMMY_VAR__);
        stan::math::assign(BxA,(get_base1(phi,3,"phi",1) + (get_base1(phi,4,"phi",1) * get_base1(theta,2,"theta",1))));
        current_statement_begin__ = 16;
        local_scalar_t__ BxR;
        (void) BxR;  // dummy to suppress unused var warning

        stan::math::initialize(BxR, DUMMY_VAR__);
        stan::math::fill(BxR,DUMMY_VAR__);
        stan::math::assign(BxR,(get_base1(phi,5,"phi",1) + (get_base1(phi,6,"phi",1) * get_base1(theta,3,"theta",1))));
        current_statement_begin__ = 17;
        local_scalar_t__ BtA;
        (void) BtA;  // dummy to suppress unused var warning

        stan::math::initialize(BtA, DUMMY_VAR__);
        stan::math::fill(BtA,DUMMY_VAR__);
        stan::math::assign(BtA,(get_base1(phi,7,"phi",1) + (get_base1(phi,8,"phi",1) * get_base1(theta,4,"theta",1))));
        current_statement_begin__ = 18;
        local_scalar_t__ BtR;
        (void) BtR;  // dummy to suppress unused var warning

        stan::math::initialize(BtR, DUMMY_VAR__);
        stan::math::fill(BtR,DUMMY_VAR__);
        stan::math::assign(BtR,(get_base1(phi,9,"phi",1) + (get_base1(phi,10,"phi",1) * get_base1(theta,5,"theta",1))));
        current_statement_begin__ = 22;
        validate_non_negative_index("y", "Nvalid", Nvalid);
        vector<int> y(Nvalid, 0);
        stan::math::fill(y, std::numeric_limits<int>::min());
        current_statement_begin__ = 23;
        validate_non_negative_index("p_a_logit", "Nvalid", Nvalid);
        Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  p_a_logit(static_cast<Eigen::VectorXd::Index>(Nvalid));
        (void) p_a_logit;  // dummy to suppress unused var warning

        stan::math::initialize(p_a_logit, DUMMY_VAR__);
        stan::math::fill(p_a_logit,DUMMY_VAR__);
        current_statement_begin__ = 24;
        local_scalar_t__ m_a;
        (void) m_a;  // dummy to suppress unused var warning

        stan::math::initialize(m_a, DUMMY_VAR__);
        stan::math::fill(m_a,DUMMY_VAR__);
        current_statement_begin__ = 25;
        local_scalar_t__ m_b;
        (void) m_b;  // dummy to suppress unused var warning

        stan::math::initialize(m_b, DUMMY_VAR__);
        stan::math::fill(m_b,DUMMY_VAR__);
        current_statement_begin__ = 26;
        local_scalar_t__ d_a;
        (void) d_a;  // dummy to suppress unused var warning

        stan::math::initialize(d_a, DUMMY_VAR__);
        stan::math::fill(d_a,DUMMY_VAR__);
        current_statement_begin__ = 27;
        local_scalar_t__ d_b;
        (void) d_b;  // dummy to suppress unused var warning

        stan::math::initialize(d_b, DUMMY_VAR__);
        stan::math::fill(d_b,DUMMY_VAR__);
        current_statement_begin__ = 28;
        local_scalar_t__ mean_x;
        (void) mean_x;  // dummy to suppress unused var warning

        stan::math::initialize(mean_x, DUMMY_VAR__);
        stan::math::fill(mean_x,DUMMY_VAR__);
        current_statement_begin__ = 29;
        local_scalar_t__ mean_t;
        (void) mean_t;  // dummy to suppress unused var warning

        stan::math::initialize(mean_t, DUMMY_VAR__);
        stan::math::fill(mean_t,DUMMY_VAR__);
        current_statement_begin__ = 30;
        local_scalar_t__ xA;
        (void) xA;  // dummy to suppress unused var warning

        stan::math::initialize(xA, DUMMY_VAR__);
        stan::math::fill(xA,DUMMY_VAR__);
        current_statement_begin__ = 31;
        local_scalar_t__ xR;
        (void) xR;  // dummy to suppress unused var warning

        stan::math::initialize(xR, DUMMY_VAR__);
        stan::math::fill(xR,DUMMY_VAR__);
        current_statement_begin__ = 32;
        local_scalar_t__ tA;
        (void) tA;  // dummy to suppress unused var warning

        stan::math::initialize(tA, DUMMY_VAR__);
        stan::math::fill(tA,DUMMY_VAR__);
        current_statement_begin__ = 33;
        local_scalar_t__ tR;
        (void) tR;  // dummy to suppress unused var warning

        stan::math::initialize(tR, DUMMY_VAR__);
        stan::math::fill(tR,DUMMY_VAR__);
        current_statement_begin__ = 34;
        local_scalar_t__ lp;
        (void) lp;  // dummy to suppress unused var warning

        stan::math::initialize(lp, DUMMY_VAR__);
        stan::math::fill(lp,DUMMY_VAR__);


        current_statement_begin__ = 36;
        for (int i = 1; i <= Nvalid; ++i) {

            current_statement_begin__ = 37;
            stan::math::assign(m_a, get_base1(real_data,i,"real_data",1));
            current_statement_begin__ = 38;
            stan::math::assign(m_b, get_base1(real_data,(Nplaces + i),"real_data",1));
            current_statement_begin__ = 39;
            stan::math::assign(d_a, get_base1(real_data,((2 * Nplaces) + i),"real_data",1));
            current_statement_begin__ = 40;
            stan::math::assign(d_b, get_base1(real_data,((3 * Nplaces) + i),"real_data",1));
            current_statement_begin__ = 42;
            stan::math::assign(mean_x, stan::math::fmax(((m_a + m_b) / 2),1e-10));
            current_statement_begin__ = 43;
            stan::math::assign(mean_t, stan::math::fmax(((d_a + d_b) / 2),1e-10));
            current_statement_begin__ = 45;
            stan::math::assign(xA, (m_a - m_b));
            current_statement_begin__ = 46;
            stan::math::assign(xR, ((m_a - m_b) / mean_x));
            current_statement_begin__ = 47;
            stan::math::assign(tA, (d_a - d_b));
            current_statement_begin__ = 48;
            stan::math::assign(tR, ((d_a - d_b) / mean_t));
            current_statement_begin__ = 50;
            stan::model::assign(p_a_logit, 
                        stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                        ((((B1 + (BxA * xA)) + (BxR * xR)) + (BtA * tA)) + (BxR * xR)), 
                        "assigning variable p_a_logit");
            current_statement_begin__ = 52;
            stan::model::assign(y, 
                        stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                        get_base1(int_data,(2 + i),"int_data",1), 
                        "assigning variable y");
        }
        current_statement_begin__ = 55;
        stan::math::assign(lp, bernoulli_logit_log(y,p_a_logit));
        current_statement_begin__ = 57;
        return stan::math::promote_scalar<fun_return_scalar_t__>(transpose(stan::math::to_row_vector(stan::math::array_builder<local_scalar_t__ >().add(lp).array())));
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}


struct likelihood_functor__ {
    template <typename T0__, typename T1__, typename T2__>
        Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__, T2__>::type, Eigen::Dynamic,1>
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic,1>& phi,
               const Eigen::Matrix<T1__, Eigen::Dynamic,1>& theta,
               const std::vector<T2__>& real_data,
               const std::vector<int>& int_data, std::ostream* pstream__) const {
        return likelihood(phi, theta, real_data, int_data, pstream__);
    }
};

class ITCH_mpi_model : public prob_grad {
private:
    int Nsubj;
    int Max_obs_per_subj;
    vector<vector<double> > real_data;
    vector<vector<int> > int_data;
public:
    ITCH_mpi_model(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }

    ITCH_mpi_model(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }

    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;

        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning

        current_statement_begin__ = -1;

        static const char* function__ = "ITCH_mpi_model_namespace::ITCH_mpi_model";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        // initialize member variables
        try {
            current_statement_begin__ = 62;
            context__.validate_dims("data initialization", "Nsubj", "int", context__.to_vec());
            Nsubj = int(0);
            vals_i__ = context__.vals_i("Nsubj");
            pos__ = 0;
            Nsubj = vals_i__[pos__++];
            current_statement_begin__ = 63;
            context__.validate_dims("data initialization", "Max_obs_per_subj", "int", context__.to_vec());
            Max_obs_per_subj = int(0);
            vals_i__ = context__.vals_i("Max_obs_per_subj");
            pos__ = 0;
            Max_obs_per_subj = vals_i__[pos__++];
            current_statement_begin__ = 64;
            validate_non_negative_index("real_data", "Nsubj", Nsubj);
            validate_non_negative_index("real_data", "(Max_obs_per_subj * 4)", (Max_obs_per_subj * 4));
            context__.validate_dims("data initialization", "real_data", "double", context__.to_vec(Nsubj,(Max_obs_per_subj * 4)));
            validate_non_negative_index("real_data", "Nsubj", Nsubj);
            validate_non_negative_index("real_data", "(Max_obs_per_subj * 4)", (Max_obs_per_subj * 4));
            real_data = std::vector<std::vector<double> >(Nsubj,std::vector<double>((Max_obs_per_subj * 4),double(0)));
            vals_r__ = context__.vals_r("real_data");
            pos__ = 0;
            size_t real_data_limit_1__ = (Max_obs_per_subj * 4);
            for (size_t i_1__ = 0; i_1__ < real_data_limit_1__; ++i_1__) {
                size_t real_data_limit_0__ = Nsubj;
                for (size_t i_0__ = 0; i_0__ < real_data_limit_0__; ++i_0__) {
                    real_data[i_0__][i_1__] = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 65;
            validate_non_negative_index("int_data", "Nsubj", Nsubj);
            validate_non_negative_index("int_data", "(Max_obs_per_subj + 2)", (Max_obs_per_subj + 2));
            context__.validate_dims("data initialization", "int_data", "int", context__.to_vec(Nsubj,(Max_obs_per_subj + 2)));
            validate_non_negative_index("int_data", "Nsubj", Nsubj);
            validate_non_negative_index("int_data", "(Max_obs_per_subj + 2)", (Max_obs_per_subj + 2));
            int_data = std::vector<std::vector<int> >(Nsubj,std::vector<int>((Max_obs_per_subj + 2),int(0)));
            vals_i__ = context__.vals_i("int_data");
            pos__ = 0;
            size_t int_data_limit_1__ = (Max_obs_per_subj + 2);
            for (size_t i_1__ = 0; i_1__ < int_data_limit_1__; ++i_1__) {
                size_t int_data_limit_0__ = Nsubj;
                for (size_t i_0__ = 0; i_0__ < int_data_limit_0__; ++i_0__) {
                    int_data[i_0__][i_1__] = vals_i__[pos__++];
                }
            }

            // validate, data variables
            current_statement_begin__ = 62;
            current_statement_begin__ = 63;
            current_statement_begin__ = 64;
            current_statement_begin__ = 65;
            // initialize data variables


            // validate transformed data

            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 70;
            ++num_params_r__;
            current_statement_begin__ = 71;
            ++num_params_r__;
            current_statement_begin__ = 72;
            validate_non_negative_index("B1_raw", "Nsubj", Nsubj);
            num_params_r__ += Nsubj;
            current_statement_begin__ = 74;
            ++num_params_r__;
            current_statement_begin__ = 75;
            ++num_params_r__;
            current_statement_begin__ = 76;
            validate_non_negative_index("BxA_raw", "Nsubj", Nsubj);
            num_params_r__ += Nsubj;
            current_statement_begin__ = 78;
            ++num_params_r__;
            current_statement_begin__ = 79;
            ++num_params_r__;
            current_statement_begin__ = 80;
            validate_non_negative_index("BxR_raw", "Nsubj", Nsubj);
            num_params_r__ += Nsubj;
            current_statement_begin__ = 82;
            ++num_params_r__;
            current_statement_begin__ = 83;
            ++num_params_r__;
            current_statement_begin__ = 84;
            validate_non_negative_index("BtA_raw", "Nsubj", Nsubj);
            num_params_r__ += Nsubj;
            current_statement_begin__ = 86;
            ++num_params_r__;
            current_statement_begin__ = 87;
            ++num_params_r__;
            current_statement_begin__ = 88;
            validate_non_negative_index("BtR_raw", "Nsubj", Nsubj);
            num_params_r__ += Nsubj;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    ~ITCH_mpi_model() { }


    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        stan::io::writer<double> writer__(params_r__,params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;

        if (!(context__.contains_r("B1_mean")))
            throw std::runtime_error("variable B1_mean missing");
        vals_r__ = context__.vals_r("B1_mean");
        pos__ = 0U;
        context__.validate_dims("initialization", "B1_mean", "double", context__.to_vec());
        double B1_mean(0);
        B1_mean = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(B1_mean);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable B1_mean: ") + e.what());
        }

        if (!(context__.contains_r("B1_sd")))
            throw std::runtime_error("variable B1_sd missing");
        vals_r__ = context__.vals_r("B1_sd");
        pos__ = 0U;
        context__.validate_dims("initialization", "B1_sd", "double", context__.to_vec());
        double B1_sd(0);
        B1_sd = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,B1_sd);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable B1_sd: ") + e.what());
        }

        if (!(context__.contains_r("B1_raw")))
            throw std::runtime_error("variable B1_raw missing");
        vals_r__ = context__.vals_r("B1_raw");
        pos__ = 0U;
        validate_non_negative_index("B1_raw", "Nsubj", Nsubj);
        context__.validate_dims("initialization", "B1_raw", "vector_d", context__.to_vec(Nsubj));
        vector_d B1_raw(static_cast<Eigen::VectorXd::Index>(Nsubj));
        for (int j1__ = 0U; j1__ < Nsubj; ++j1__)
            B1_raw(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_unconstrain(B1_raw);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable B1_raw: ") + e.what());
        }

        if (!(context__.contains_r("BxA_mean")))
            throw std::runtime_error("variable BxA_mean missing");
        vals_r__ = context__.vals_r("BxA_mean");
        pos__ = 0U;
        context__.validate_dims("initialization", "BxA_mean", "double", context__.to_vec());
        double BxA_mean(0);
        BxA_mean = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,BxA_mean);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable BxA_mean: ") + e.what());
        }

        if (!(context__.contains_r("BxA_sd")))
            throw std::runtime_error("variable BxA_sd missing");
        vals_r__ = context__.vals_r("BxA_sd");
        pos__ = 0U;
        context__.validate_dims("initialization", "BxA_sd", "double", context__.to_vec());
        double BxA_sd(0);
        BxA_sd = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,BxA_sd);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable BxA_sd: ") + e.what());
        }

        if (!(context__.contains_r("BxA_raw")))
            throw std::runtime_error("variable BxA_raw missing");
        vals_r__ = context__.vals_r("BxA_raw");
        pos__ = 0U;
        validate_non_negative_index("BxA_raw", "Nsubj", Nsubj);
        context__.validate_dims("initialization", "BxA_raw", "vector_d", context__.to_vec(Nsubj));
        vector_d BxA_raw(static_cast<Eigen::VectorXd::Index>(Nsubj));
        for (int j1__ = 0U; j1__ < Nsubj; ++j1__)
            BxA_raw(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_lb_unconstrain(0,BxA_raw);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable BxA_raw: ") + e.what());
        }

        if (!(context__.contains_r("BxR_mean")))
            throw std::runtime_error("variable BxR_mean missing");
        vals_r__ = context__.vals_r("BxR_mean");
        pos__ = 0U;
        context__.validate_dims("initialization", "BxR_mean", "double", context__.to_vec());
        double BxR_mean(0);
        BxR_mean = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,BxR_mean);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable BxR_mean: ") + e.what());
        }

        if (!(context__.contains_r("BxR_sd")))
            throw std::runtime_error("variable BxR_sd missing");
        vals_r__ = context__.vals_r("BxR_sd");
        pos__ = 0U;
        context__.validate_dims("initialization", "BxR_sd", "double", context__.to_vec());
        double BxR_sd(0);
        BxR_sd = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,BxR_sd);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable BxR_sd: ") + e.what());
        }

        if (!(context__.contains_r("BxR_raw")))
            throw std::runtime_error("variable BxR_raw missing");
        vals_r__ = context__.vals_r("BxR_raw");
        pos__ = 0U;
        validate_non_negative_index("BxR_raw", "Nsubj", Nsubj);
        context__.validate_dims("initialization", "BxR_raw", "vector_d", context__.to_vec(Nsubj));
        vector_d BxR_raw(static_cast<Eigen::VectorXd::Index>(Nsubj));
        for (int j1__ = 0U; j1__ < Nsubj; ++j1__)
            BxR_raw(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_lb_unconstrain(0,BxR_raw);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable BxR_raw: ") + e.what());
        }

        if (!(context__.contains_r("BtA_mean")))
            throw std::runtime_error("variable BtA_mean missing");
        vals_r__ = context__.vals_r("BtA_mean");
        pos__ = 0U;
        context__.validate_dims("initialization", "BtA_mean", "double", context__.to_vec());
        double BtA_mean(0);
        BtA_mean = vals_r__[pos__++];
        try {
            writer__.scalar_ub_unconstrain(0,BtA_mean);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable BtA_mean: ") + e.what());
        }

        if (!(context__.contains_r("BtA_sd")))
            throw std::runtime_error("variable BtA_sd missing");
        vals_r__ = context__.vals_r("BtA_sd");
        pos__ = 0U;
        context__.validate_dims("initialization", "BtA_sd", "double", context__.to_vec());
        double BtA_sd(0);
        BtA_sd = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,BtA_sd);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable BtA_sd: ") + e.what());
        }

        if (!(context__.contains_r("BtA_raw")))
            throw std::runtime_error("variable BtA_raw missing");
        vals_r__ = context__.vals_r("BtA_raw");
        pos__ = 0U;
        validate_non_negative_index("BtA_raw", "Nsubj", Nsubj);
        context__.validate_dims("initialization", "BtA_raw", "vector_d", context__.to_vec(Nsubj));
        vector_d BtA_raw(static_cast<Eigen::VectorXd::Index>(Nsubj));
        for (int j1__ = 0U; j1__ < Nsubj; ++j1__)
            BtA_raw(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_ub_unconstrain(0,BtA_raw);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable BtA_raw: ") + e.what());
        }

        if (!(context__.contains_r("BtR_mean")))
            throw std::runtime_error("variable BtR_mean missing");
        vals_r__ = context__.vals_r("BtR_mean");
        pos__ = 0U;
        context__.validate_dims("initialization", "BtR_mean", "double", context__.to_vec());
        double BtR_mean(0);
        BtR_mean = vals_r__[pos__++];
        try {
            writer__.scalar_ub_unconstrain(0,BtR_mean);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable BtR_mean: ") + e.what());
        }

        if (!(context__.contains_r("BtR_sd")))
            throw std::runtime_error("variable BtR_sd missing");
        vals_r__ = context__.vals_r("BtR_sd");
        pos__ = 0U;
        context__.validate_dims("initialization", "BtR_sd", "double", context__.to_vec());
        double BtR_sd(0);
        BtR_sd = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,BtR_sd);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable BtR_sd: ") + e.what());
        }

        if (!(context__.contains_r("BtR_raw")))
            throw std::runtime_error("variable BtR_raw missing");
        vals_r__ = context__.vals_r("BtR_raw");
        pos__ = 0U;
        validate_non_negative_index("BtR_raw", "Nsubj", Nsubj);
        context__.validate_dims("initialization", "BtR_raw", "vector_d", context__.to_vec(Nsubj));
        vector_d BtR_raw(static_cast<Eigen::VectorXd::Index>(Nsubj));
        for (int j1__ = 0U; j1__ < Nsubj; ++j1__)
            BtR_raw(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_ub_unconstrain(0,BtR_raw);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable BtR_raw: ") + e.what());
        }

        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }


    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(vector<T__>& params_r__,
                 vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {

        typedef T__ local_scalar_t__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;

        try {
            // model parameters
            stan::io::reader<local_scalar_t__> in__(params_r__,params_i__);

            local_scalar_t__ B1_mean;
            (void) B1_mean;  // dummy to suppress unused var warning
            if (jacobian__)
                B1_mean = in__.scalar_constrain(lp__);
            else
                B1_mean = in__.scalar_constrain();

            local_scalar_t__ B1_sd;
            (void) B1_sd;  // dummy to suppress unused var warning
            if (jacobian__)
                B1_sd = in__.scalar_lb_constrain(0,lp__);
            else
                B1_sd = in__.scalar_lb_constrain(0);

            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  B1_raw;
            (void) B1_raw;  // dummy to suppress unused var warning
            if (jacobian__)
                B1_raw = in__.vector_constrain(Nsubj,lp__);
            else
                B1_raw = in__.vector_constrain(Nsubj);

            local_scalar_t__ BxA_mean;
            (void) BxA_mean;  // dummy to suppress unused var warning
            if (jacobian__)
                BxA_mean = in__.scalar_lb_constrain(0,lp__);
            else
                BxA_mean = in__.scalar_lb_constrain(0);

            local_scalar_t__ BxA_sd;
            (void) BxA_sd;  // dummy to suppress unused var warning
            if (jacobian__)
                BxA_sd = in__.scalar_lb_constrain(0,lp__);
            else
                BxA_sd = in__.scalar_lb_constrain(0);

            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  BxA_raw;
            (void) BxA_raw;  // dummy to suppress unused var warning
            if (jacobian__)
                BxA_raw = in__.vector_lb_constrain(0,Nsubj,lp__);
            else
                BxA_raw = in__.vector_lb_constrain(0,Nsubj);

            local_scalar_t__ BxR_mean;
            (void) BxR_mean;  // dummy to suppress unused var warning
            if (jacobian__)
                BxR_mean = in__.scalar_lb_constrain(0,lp__);
            else
                BxR_mean = in__.scalar_lb_constrain(0);

            local_scalar_t__ BxR_sd;
            (void) BxR_sd;  // dummy to suppress unused var warning
            if (jacobian__)
                BxR_sd = in__.scalar_lb_constrain(0,lp__);
            else
                BxR_sd = in__.scalar_lb_constrain(0);

            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  BxR_raw;
            (void) BxR_raw;  // dummy to suppress unused var warning
            if (jacobian__)
                BxR_raw = in__.vector_lb_constrain(0,Nsubj,lp__);
            else
                BxR_raw = in__.vector_lb_constrain(0,Nsubj);

            local_scalar_t__ BtA_mean;
            (void) BtA_mean;  // dummy to suppress unused var warning
            if (jacobian__)
                BtA_mean = in__.scalar_ub_constrain(0,lp__);
            else
                BtA_mean = in__.scalar_ub_constrain(0);

            local_scalar_t__ BtA_sd;
            (void) BtA_sd;  // dummy to suppress unused var warning
            if (jacobian__)
                BtA_sd = in__.scalar_lb_constrain(0,lp__);
            else
                BtA_sd = in__.scalar_lb_constrain(0);

            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  BtA_raw;
            (void) BtA_raw;  // dummy to suppress unused var warning
            if (jacobian__)
                BtA_raw = in__.vector_ub_constrain(0,Nsubj,lp__);
            else
                BtA_raw = in__.vector_ub_constrain(0,Nsubj);

            local_scalar_t__ BtR_mean;
            (void) BtR_mean;  // dummy to suppress unused var warning
            if (jacobian__)
                BtR_mean = in__.scalar_ub_constrain(0,lp__);
            else
                BtR_mean = in__.scalar_ub_constrain(0);

            local_scalar_t__ BtR_sd;
            (void) BtR_sd;  // dummy to suppress unused var warning
            if (jacobian__)
                BtR_sd = in__.scalar_lb_constrain(0,lp__);
            else
                BtR_sd = in__.scalar_lb_constrain(0);

            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  BtR_raw;
            (void) BtR_raw;  // dummy to suppress unused var warning
            if (jacobian__)
                BtR_raw = in__.vector_ub_constrain(0,Nsubj,lp__);
            else
                BtR_raw = in__.vector_ub_constrain(0,Nsubj);


            // transformed parameters
            current_statement_begin__ = 96;
            validate_non_negative_index("phi", "10", 10);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  phi(static_cast<Eigen::VectorXd::Index>(10));
            (void) phi;  // dummy to suppress unused var warning

            stan::math::initialize(phi, DUMMY_VAR__);
            stan::math::fill(phi,DUMMY_VAR__);
            current_statement_begin__ = 97;
            validate_non_negative_index("theta", "5", 5);
            validate_non_negative_index("theta", "Nsubj", Nsubj);
            vector<Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1> > theta(Nsubj, (Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1> (static_cast<Eigen::VectorXd::Index>(5))));
            stan::math::initialize(theta, DUMMY_VAR__);
            stan::math::fill(theta,DUMMY_VAR__);


            current_statement_begin__ = 100;
            stan::model::assign(phi, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                        B1_mean, 
                        "assigning variable phi");
            current_statement_begin__ = 101;
            stan::model::assign(phi, 
                        stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()), 
                        B1_sd, 
                        "assigning variable phi");
            current_statement_begin__ = 102;
            stan::model::assign(phi, 
                        stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list()), 
                        BxA_mean, 
                        "assigning variable phi");
            current_statement_begin__ = 103;
            stan::model::assign(phi, 
                        stan::model::cons_list(stan::model::index_uni(4), stan::model::nil_index_list()), 
                        BxA_sd, 
                        "assigning variable phi");
            current_statement_begin__ = 104;
            stan::model::assign(phi, 
                        stan::model::cons_list(stan::model::index_uni(5), stan::model::nil_index_list()), 
                        BxR_mean, 
                        "assigning variable phi");
            current_statement_begin__ = 105;
            stan::model::assign(phi, 
                        stan::model::cons_list(stan::model::index_uni(6), stan::model::nil_index_list()), 
                        BxR_sd, 
                        "assigning variable phi");
            current_statement_begin__ = 106;
            stan::model::assign(phi, 
                        stan::model::cons_list(stan::model::index_uni(7), stan::model::nil_index_list()), 
                        BtA_mean, 
                        "assigning variable phi");
            current_statement_begin__ = 107;
            stan::model::assign(phi, 
                        stan::model::cons_list(stan::model::index_uni(8), stan::model::nil_index_list()), 
                        BtA_sd, 
                        "assigning variable phi");
            current_statement_begin__ = 108;
            stan::model::assign(phi, 
                        stan::model::cons_list(stan::model::index_uni(9), stan::model::nil_index_list()), 
                        BtR_mean, 
                        "assigning variable phi");
            current_statement_begin__ = 109;
            stan::model::assign(phi, 
                        stan::model::cons_list(stan::model::index_uni(10), stan::model::nil_index_list()), 
                        BtR_sd, 
                        "assigning variable phi");
            current_statement_begin__ = 112;
            for (int subj = 1; subj <= Nsubj; ++subj) {

                current_statement_begin__ = 113;
                stan::model::assign(theta, 
                            stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                            get_base1(B1_raw,subj,"B1_raw",1), 
                            "assigning variable theta");
                current_statement_begin__ = 114;
                stan::model::assign(theta, 
                            stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list())), 
                            get_base1(BxA_raw,subj,"BxA_raw",1), 
                            "assigning variable theta");
                current_statement_begin__ = 115;
                stan::model::assign(theta, 
                            stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list())), 
                            get_base1(BxR_raw,subj,"BxR_raw",1), 
                            "assigning variable theta");
                current_statement_begin__ = 116;
                stan::model::assign(theta, 
                            stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(4), stan::model::nil_index_list())), 
                            get_base1(BtA_raw,subj,"BtA_raw",1), 
                            "assigning variable theta");
                current_statement_begin__ = 117;
                stan::model::assign(theta, 
                            stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(5), stan::model::nil_index_list())), 
                            get_base1(BtR_raw,subj,"BtR_raw",1), 
                            "assigning variable theta");
            }

            // validate transformed parameters
            for (int i0__ = 0; i0__ < 10; ++i0__) {
                if (stan::math::is_uninitialized(phi(i0__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: phi" << '[' << i0__ << ']';
                    throw std::runtime_error(msg__.str());
                }
            }
            for (int i0__ = 0; i0__ < Nsubj; ++i0__) {
                for (int i1__ = 0; i1__ < 5; ++i1__) {
                    if (stan::math::is_uninitialized(theta[i0__](i1__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: theta" << '[' << i0__ << ']' << '[' << i1__ << ']';
                        throw std::runtime_error(msg__.str());
                    }
                }
            }

            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 96;
            current_statement_begin__ = 97;

            // model body

            current_statement_begin__ = 125;
            lp_accum__.add(normal_log<propto__>(B1_mean, 0, 1));
            current_statement_begin__ = 126;
            lp_accum__.add(normal_log<propto__>(B1_sd, 0, 1));
            current_statement_begin__ = 128;
            lp_accum__.add(normal_log<propto__>(BxA_mean, 0, 1));
            current_statement_begin__ = 129;
            lp_accum__.add(normal_log<propto__>(BxA_sd, 0, 1));
            current_statement_begin__ = 131;
            lp_accum__.add(normal_log<propto__>(BxR_mean, 0, 1));
            current_statement_begin__ = 132;
            lp_accum__.add(normal_log<propto__>(BxR_sd, 0, 1));
            current_statement_begin__ = 134;
            lp_accum__.add(normal_log<propto__>(BtA_mean, 0, 1));
            current_statement_begin__ = 135;
            lp_accum__.add(normal_log<propto__>(BtA_sd, 0, 1));
            current_statement_begin__ = 137;
            lp_accum__.add(normal_log<propto__>(BtR_mean, 0, 1));
            current_statement_begin__ = 138;
            lp_accum__.add(normal_log<propto__>(BtR_sd, 0, 1));
            current_statement_begin__ = 140;
            lp_accum__.add(normal_log<propto__>(B1_raw, 0, 1));
            current_statement_begin__ = 141;
            lp_accum__.add(normal_log<propto__>(BxA_raw, 0, 1));
            current_statement_begin__ = 142;
            lp_accum__.add(normal_log<propto__>(BxR_raw, 0, 1));
            current_statement_begin__ = 143;
            lp_accum__.add(normal_log<propto__>(BtA_raw, 0, 1));
            current_statement_begin__ = 144;
            lp_accum__.add(normal_log<propto__>(BtR_raw, 0, 1));
            current_statement_begin__ = 147;
            lp_accum__.add(sum(map_rect<1, likelihood_functor__>(phi, theta, real_data, int_data, pstream__)));

        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        lp_accum__.add(lp__);
        return lp_accum__.sum();

    } // log_prob()

    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }


    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("B1_mean");
        names__.push_back("B1_sd");
        names__.push_back("B1_raw");
        names__.push_back("BxA_mean");
        names__.push_back("BxA_sd");
        names__.push_back("BxA_raw");
        names__.push_back("BxR_mean");
        names__.push_back("BxR_sd");
        names__.push_back("BxR_raw");
        names__.push_back("BtA_mean");
        names__.push_back("BtA_sd");
        names__.push_back("BtA_raw");
        names__.push_back("BtR_mean");
        names__.push_back("BtR_sd");
        names__.push_back("BtR_raw");
        names__.push_back("phi");
        names__.push_back("theta");
    }


    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Nsubj);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Nsubj);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Nsubj);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Nsubj);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Nsubj);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(10);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Nsubj);
        dims__.push_back(5);
        dimss__.push_back(dims__);
    }

    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;

        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__,params_i__);
        static const char* function__ = "ITCH_mpi_model_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double B1_mean = in__.scalar_constrain();
        double B1_sd = in__.scalar_lb_constrain(0);
        vector_d B1_raw = in__.vector_constrain(Nsubj);
        double BxA_mean = in__.scalar_lb_constrain(0);
        double BxA_sd = in__.scalar_lb_constrain(0);
        vector_d BxA_raw = in__.vector_lb_constrain(0,Nsubj);
        double BxR_mean = in__.scalar_lb_constrain(0);
        double BxR_sd = in__.scalar_lb_constrain(0);
        vector_d BxR_raw = in__.vector_lb_constrain(0,Nsubj);
        double BtA_mean = in__.scalar_ub_constrain(0);
        double BtA_sd = in__.scalar_lb_constrain(0);
        vector_d BtA_raw = in__.vector_ub_constrain(0,Nsubj);
        double BtR_mean = in__.scalar_ub_constrain(0);
        double BtR_sd = in__.scalar_lb_constrain(0);
        vector_d BtR_raw = in__.vector_ub_constrain(0,Nsubj);
        vars__.push_back(B1_mean);
        vars__.push_back(B1_sd);
            for (int k_0__ = 0; k_0__ < Nsubj; ++k_0__) {
            vars__.push_back(B1_raw[k_0__]);
            }
        vars__.push_back(BxA_mean);
        vars__.push_back(BxA_sd);
            for (int k_0__ = 0; k_0__ < Nsubj; ++k_0__) {
            vars__.push_back(BxA_raw[k_0__]);
            }
        vars__.push_back(BxR_mean);
        vars__.push_back(BxR_sd);
            for (int k_0__ = 0; k_0__ < Nsubj; ++k_0__) {
            vars__.push_back(BxR_raw[k_0__]);
            }
        vars__.push_back(BtA_mean);
        vars__.push_back(BtA_sd);
            for (int k_0__ = 0; k_0__ < Nsubj; ++k_0__) {
            vars__.push_back(BtA_raw[k_0__]);
            }
        vars__.push_back(BtR_mean);
        vars__.push_back(BtR_sd);
            for (int k_0__ = 0; k_0__ < Nsubj; ++k_0__) {
            vars__.push_back(BtR_raw[k_0__]);
            }

        // declare and define transformed parameters
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        try {
            current_statement_begin__ = 96;
            validate_non_negative_index("phi", "10", 10);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  phi(static_cast<Eigen::VectorXd::Index>(10));
            (void) phi;  // dummy to suppress unused var warning

            stan::math::initialize(phi, DUMMY_VAR__);
            stan::math::fill(phi,DUMMY_VAR__);
            current_statement_begin__ = 97;
            validate_non_negative_index("theta", "5", 5);
            validate_non_negative_index("theta", "Nsubj", Nsubj);
            vector<Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1> > theta(Nsubj, (Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1> (static_cast<Eigen::VectorXd::Index>(5))));
            stan::math::initialize(theta, DUMMY_VAR__);
            stan::math::fill(theta,DUMMY_VAR__);


            current_statement_begin__ = 100;
            stan::model::assign(phi, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                        B1_mean, 
                        "assigning variable phi");
            current_statement_begin__ = 101;
            stan::model::assign(phi, 
                        stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()), 
                        B1_sd, 
                        "assigning variable phi");
            current_statement_begin__ = 102;
            stan::model::assign(phi, 
                        stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list()), 
                        BxA_mean, 
                        "assigning variable phi");
            current_statement_begin__ = 103;
            stan::model::assign(phi, 
                        stan::model::cons_list(stan::model::index_uni(4), stan::model::nil_index_list()), 
                        BxA_sd, 
                        "assigning variable phi");
            current_statement_begin__ = 104;
            stan::model::assign(phi, 
                        stan::model::cons_list(stan::model::index_uni(5), stan::model::nil_index_list()), 
                        BxR_mean, 
                        "assigning variable phi");
            current_statement_begin__ = 105;
            stan::model::assign(phi, 
                        stan::model::cons_list(stan::model::index_uni(6), stan::model::nil_index_list()), 
                        BxR_sd, 
                        "assigning variable phi");
            current_statement_begin__ = 106;
            stan::model::assign(phi, 
                        stan::model::cons_list(stan::model::index_uni(7), stan::model::nil_index_list()), 
                        BtA_mean, 
                        "assigning variable phi");
            current_statement_begin__ = 107;
            stan::model::assign(phi, 
                        stan::model::cons_list(stan::model::index_uni(8), stan::model::nil_index_list()), 
                        BtA_sd, 
                        "assigning variable phi");
            current_statement_begin__ = 108;
            stan::model::assign(phi, 
                        stan::model::cons_list(stan::model::index_uni(9), stan::model::nil_index_list()), 
                        BtR_mean, 
                        "assigning variable phi");
            current_statement_begin__ = 109;
            stan::model::assign(phi, 
                        stan::model::cons_list(stan::model::index_uni(10), stan::model::nil_index_list()), 
                        BtR_sd, 
                        "assigning variable phi");
            current_statement_begin__ = 112;
            for (int subj = 1; subj <= Nsubj; ++subj) {

                current_statement_begin__ = 113;
                stan::model::assign(theta, 
                            stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                            get_base1(B1_raw,subj,"B1_raw",1), 
                            "assigning variable theta");
                current_statement_begin__ = 114;
                stan::model::assign(theta, 
                            stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list())), 
                            get_base1(BxA_raw,subj,"BxA_raw",1), 
                            "assigning variable theta");
                current_statement_begin__ = 115;
                stan::model::assign(theta, 
                            stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list())), 
                            get_base1(BxR_raw,subj,"BxR_raw",1), 
                            "assigning variable theta");
                current_statement_begin__ = 116;
                stan::model::assign(theta, 
                            stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(4), stan::model::nil_index_list())), 
                            get_base1(BtA_raw,subj,"BtA_raw",1), 
                            "assigning variable theta");
                current_statement_begin__ = 117;
                stan::model::assign(theta, 
                            stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(5), stan::model::nil_index_list())), 
                            get_base1(BtR_raw,subj,"BtR_raw",1), 
                            "assigning variable theta");
            }

            // validate transformed parameters
            current_statement_begin__ = 96;
            current_statement_begin__ = 97;

            // write transformed parameters
            if (include_tparams__) {
            for (int k_0__ = 0; k_0__ < 10; ++k_0__) {
            vars__.push_back(phi[k_0__]);
            }
            for (int k_1__ = 0; k_1__ < 5; ++k_1__) {
                for (int k_0__ = 0; k_0__ < Nsubj; ++k_0__) {
                vars__.push_back(theta[k_0__][k_1__]);
                }
            }
            }
            if (!include_gqs__) return;
            // declare and define generated quantities



            // validate generated quantities

            // write generated quantities
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng,params_r_vec,params_i_vec,vars_vec,include_tparams,include_gqs,pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    static std::string model_name() {
        return "ITCH_mpi_model";
    }


    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "B1_mean";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "B1_sd";
        param_names__.push_back(param_name_stream__.str());
        for (int k_0__ = 1; k_0__ <= Nsubj; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "B1_raw" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "BxA_mean";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "BxA_sd";
        param_names__.push_back(param_name_stream__.str());
        for (int k_0__ = 1; k_0__ <= Nsubj; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "BxA_raw" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "BxR_mean";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "BxR_sd";
        param_names__.push_back(param_name_stream__.str());
        for (int k_0__ = 1; k_0__ <= Nsubj; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "BxR_raw" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "BtA_mean";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "BtA_sd";
        param_names__.push_back(param_name_stream__.str());
        for (int k_0__ = 1; k_0__ <= Nsubj; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "BtA_raw" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "BtR_mean";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "BtR_sd";
        param_names__.push_back(param_name_stream__.str());
        for (int k_0__ = 1; k_0__ <= Nsubj; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "BtR_raw" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
            for (int k_0__ = 1; k_0__ <= 10; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "phi" << '.' << k_0__;
                param_names__.push_back(param_name_stream__.str());
            }
            for (int k_1__ = 1; k_1__ <= 5; ++k_1__) {
                for (int k_0__ = 1; k_0__ <= Nsubj; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "theta" << '.' << k_0__ << '.' << k_1__;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }


        if (!include_gqs__) return;
    }


    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "B1_mean";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "B1_sd";
        param_names__.push_back(param_name_stream__.str());
        for (int k_0__ = 1; k_0__ <= Nsubj; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "B1_raw" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "BxA_mean";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "BxA_sd";
        param_names__.push_back(param_name_stream__.str());
        for (int k_0__ = 1; k_0__ <= Nsubj; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "BxA_raw" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "BxR_mean";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "BxR_sd";
        param_names__.push_back(param_name_stream__.str());
        for (int k_0__ = 1; k_0__ <= Nsubj; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "BxR_raw" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "BtA_mean";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "BtA_sd";
        param_names__.push_back(param_name_stream__.str());
        for (int k_0__ = 1; k_0__ <= Nsubj; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "BtA_raw" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "BtR_mean";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "BtR_sd";
        param_names__.push_back(param_name_stream__.str());
        for (int k_0__ = 1; k_0__ <= Nsubj; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "BtR_raw" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
            for (int k_0__ = 1; k_0__ <= 10; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "phi" << '.' << k_0__;
                param_names__.push_back(param_name_stream__.str());
            }
            for (int k_1__ = 1; k_1__ <= 5; ++k_1__) {
                for (int k_0__ = 1; k_0__ <= Nsubj; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "theta" << '.' << k_0__ << '.' << k_1__;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }


        if (!include_gqs__) return;
    }

}; // model

}

typedef ITCH_mpi_model_namespace::ITCH_mpi_model stan_model;

STAN_REGISTER_MAP_RECT(1, ITCH_mpi_model_namespace::likelihood_functor__)
